- library-docker/Dockerfile
- library-docker/bin/library-to-catalog.py
This extra encoding (the file is already UTF-8 encoded) makes PyYAML encode it as binary
Data from those fields is thus not directly readable
Code was already compat with py2 (used on previous server) and py3 (used in this container).
Python version bundled in this container has a different behavior ; fixed by changing `yaml.safe_dump()` params.
Tested inside the container ; confirms it now works as expected.
Please **merge and deploy** ASAP as this break kiwix-hotspot
> Removed extra UTF-8 encoding on name/description fields

- reverse-proxy-docker/sites/default_server
Add a default_server so incorrect-domain requests don't end up on first server (download.openzim.org)
> Default server for reverse-proxy

- reverse-proxy-docker/Dockerfile
Previous PR from @kelson42 fixed the binary being compressed issue but did not include the proper MIME for OPDS (`application/atom+xml`). I also added `text/html`.
`Content-Type: application/atom+xml;profile=opds-catalog;kind=acquisition; charset=utf-8`
> Added application/atom+xml to allow compression of OPDS content

- reverse-proxy-docker/Dockerfile
Although it is temporary (until we switch to OPDS), we shall enable web-server compression on `ideascube.yml` as it is currently 1.1MB large.
Since this content is served by mirror, we can only act on `mirror.download`.
On this server, compression is already enabled but it doesn't apply to `ideascube.yml`:
```
curl -I -H "Accept-encoding: gzip" http://mirror.download.kiwix.org/library/library_zim.xml
Content-Type: text/xml
Content-Encoding: gzip
```
```
curl -I -H "Accept-encoding: gzip" http://mirror.download.kiwix.org/library/ideascube.yml
Content-Type: application/octet-stream
```
FYI, mime is wrong for this file:
```
file -i /data/download/library/ideascube.yml
/data/download/library/ideascube.yml: text/x-makefile; charset=us-ascii
```
This PR adds a new mime `text/yaml` for files …
> Enable gzip compression for YAML library

- docker-compose.yml
docker-compose YAML interprets the quotes as part of the value of the environ vs the former bash script. With this wrong URL, warehouse can't auth requests and uploads are rejected.
fixed manually on server to validate solution.
> fix cardshop warehouse env

- reverse-proxy-docker/Dockerfile
Adding user `nginx` to the `users` (`gid 100`) group in its image to fix openzim/zimfarm/issues/374 (explaination there)
> add nginx user to group users

- matomo-server-docker/data/web/vhost.d/matomo.conf
- matomo-server-docker/docker-compose.yml
* added nginx vhost conf into repo
* changed volume to point to this folder
* changed `client_body_buffer_size` for performance:
matomo web server logs are full of warnings like
```
172.31.0.10 - - [31/Mar/2020:08:17:21 +0000] "POST /piwik.php HTTP/1.1" 200 78 "-" "Matomo/LogImport" "-"
2020/03/31 08:17:21 [warn] 8#8: *5757212 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000391690, client: 172.31.0.10, server: stats.kiwix.org, request: "POST /piwik.php HTTP/1.1", host: "stats.kiwix.org"
```
This means that for every request of the matomo log import script (every 200 lines of log), nginx has to write the request to the disk and read it from there and delete it after passing it to php. It's a big waste of resources and dramatically slows down the …
> Fixes #123: include matomo nginx vhost to repo

- campusafrica/kalite-docker/kalite-setup.sh
- campusafrica/logger/entrypoint.sh
- library-docker/Dockerfile
- library-docker/bin/restart-kiwix-serve.sh
- library-docker/bin/start.sh
- library-docker/varnish/default.vcl
Varnish config:
- homepage is cached for 1d
- /skin/* (toolbar stuff) is cached for 1d
- /catalog/* is cached for 1d
- homepage favicons
- all other requests are forwarded to kiwix-serve
Dockerfile updates:
- installed curl to fix is_alive kiwix-serve test (was broken)
- installed latest varnish version from upstream deb
- apt-install command split into multiple lines for readability
- added varnish clear cache on library update
- changed Dockerfile command to varnish
Having varnish as CMD is cleaner as we are now obeying docker convention to have one
main process for the image and this process responds friendly to stop requests (unlike kiwix-serve)
Entrypoint updates
- made start.sh the entrypoint instead of command (makes more sense)
- moved kiwix-serve startup/restart/watch to …
> Varnish cache frontend

- reverse-proxy-docker/Dockerfile
- reverse-proxy-docker/sites/library.kiwix.org_location
For some reason, nginx is not capable of correctly matching our OPDS response with the
`application/atom+xml` mime-type, resulting in those requests being excluded from the gzip compression
That's because we list the `gzip_types` with support ; including `application/atom+xml`.
Kiwix-serve's response have a `Content-Type: application/atom+xml;profile=opds-catalog;kind=acquisition; charset=utf-8` which is correct according to [Wikipedia](https://en.wikipedia.org/wiki/Open_Publication_Distribution_System): `application/atom+xml;profile=opds-catalog` and [the spec](https://specs.opds.io/opds-1.2.html)
It is possible nginx only removes the part after the last `;` character to extract the mime-type from `Content-Type` header.
Nginx having a limitation in the number of character for a mime-type …
> gzip all requests on /catalog/ 

- docker-compose.yml
- reverse-proxy-docker/docker-entrypoint.sh
- vhost.d/library.kiwix.org_location
Actually, the custom reverse-proxy-docker image overwrites the `/etc/nginx/vhost.d/library.kiwix.org_location` file on startup so that's the place to insert our catalog rule.
Given this is in the image, reverting previous changes to docker-compose and repo.
> Move gzip-opds to reverse-proxy's entrypoint

- library-docker/Dockerfile
kiwix-serve being started via cron, its process doesn't inherit the host's docker
limits but uses the ones defined in its `/etc/security/limits.conf`.
As this was empty, it defaulted to `1024` open files.
By setting this to `42000` (value copied from host) kiwix-serve can open its many fds.
Tests showed with current library, it needs under 7,000.
> Fix open files issue with kiwix-serve library

- library-docker/Dockerfile
Fixes #148 
I am not sure why it used to work and why it failed to work but also setting the soft limit for the root user prevents it from falling into the default `1024` open fds.
Tested online, currently works as expected.
> Apply nofile limits to root user as well

- docker-compose.yml
cardshop now uses S3 to upload and download images
> removed cardshop containers and vhost

- docker-compose.yml
Due to the current high load of the server and the fact we don't currently look at logs, we are disabling the quarantine.
> disabled quarantine for now

- library-docker/bin/library-to-catalog/library-to-catalog.py
We make a HEAD request on ZIM files to find the actual size of the files.
Reusing the in-library URL, we'd end-up on whatever mirror while doing this.
We thus could end-up on HTTPS mirror while this doesn't handle it properly.
Make more sense to use the local server anyway (even though we go up the network stack)
> Use our mirror to check size

- library-docker/bin/library-to-catalog/library-to-catalog.py
Stop using specific mirror for url in ideascube YAML catalog
> back to using mirror manager

- library-docker/bin/manageContentRepository.pl
Hotspot versions uses the following images (hardcoded):
- `v2.3.8`: `/hotspots/base/hotspot-master_2019-08-24.img.zip`
- `v2.4.0`: `/release/kiwix-hotspot/master-images/2021-04-20/hotspot-master_2021-04-20_80c5f8e.img.zip`
- `v2.4.1`: `/release/kiwix-hotspot/master/kiwix-hostpot_master_2021-04-20.img.zip`  [bad]
- `v2.4.2`: `/release/kiwix-hotspot/master/kiwix-hostpot_master_2021-04-27.img.zip`
So we need to keep all those URLs working, except for the `2.4.1` one which is condemned.
It means we need the following files on server:
- `/release/kiwix-hotspot/master/kiwix-hostpot_master_2019-08-24.img.zip` for `<=2.3.8`, redir target from `/hotspots/base/hotspot-master_2019-08-24.img.zip`
- `/release/kiwix-hotspot/master/kiwix-hotspot_master_2021-04-22.img.zip` for `2.4.0` (it has …
> Fixed hotspot 2.4.0 master redirect

- library-docker/bin/library-to-catalog/library-to-catalog.py
- library-docker/bin/library-to-catalog/requirements.pip
In order to adapt Kiwix Hotspot behavior based on Service Worker dependency, we need
the catalog to have that information in the first place.
This adds a new `sw:y` property to items that rely on service worker (ie. have the `_sw:yes` tag)
This was done specifically as to not increase much the size of this already quite large
catalog and the fact that we want to retire it soon in favor of OPDS.
Used this oportunity to update PyYAML and use the C libyaml parser to boost performances.
> Include service worker info to ideascube catalog

- docker-compose.yml
Add an instance of https://github.com/openzim/zimfarm/tree/master/watcher to our compose.
Options are all passed on CLI but S3_URL and ZIMFARM_PASSWORD which are set in secrets.
Currently, it uses the `--dont-schedule-on-update` option as the sotoki scraper is not
ready.
> Add zimfarm-watcher container

- docker-compose.yml
[PureFTPd image](https://github.com/gimoh/docker-pureftpd) we use doesn't seem to (at least easily) turn off RW for anonymous users.
Usage recommend to use filesystem's permissions for such use case.
As we want to prevent any accidental permission mistake to allow anonymous users to
upload files on the server, mounting the whole /data/download volume read-only seems
like a very safe option.
> Prevent RW access from FTP in download folder

- docker-compose.yml
- netdata/Dockerfile
- netdata/README.md
- netdata/entrypoint.sh
- netdata/netdata.conf
- reverse-proxy-docker/sites/monitoring.openzim.org
A netdata container to receive the streams from Zimfarm monitors.
Also serves as a monitor for the server itself.
See README for additional details
> Main monitoring container

- docker-compose.yml
- reverse-proxy-docker/Dockerfile
- reverse-proxy-docker/sites/monitoring.openzim.org
Root cause was the fact that monitoring is using a custom vhost file.
In this case, it is required to include /etc/nginx/vhost.d/default
in the configuration as this file is on the shared volume between
nginx-proxy and acme-companion and is responsible for exposing the acme-challenge path.
Using this oportunity to update our base images to the latest compatible version
> Fixed #194: fixed certs renewal for monitoring and drive

- docker-compose.yml
Must point to container name as per the doc
https://docs.docker.com/compose/compose-file/compose-file-v3/#links
> Fixed mirrorbrain database links

- docker-compose.yml
Adding another drive for offspot projects.
This would mainly replaces the download.kiwix.org/other/ folder.
Chose `drive.offspot.it` but any other could do it.
> Adding offspot drive

- library-docker/bin/manageLibraryKiwixOrg.pl
We use now HTTPs links for ZIMs
> We use now HTTPs links for ZIM files

- .github/workflows/docker.yml
- matomo-server-docker/Dockerfile-app
- matomo-server-docker/docker-compose.yml
- Adding config.ini.php to image although it is in our mountpoint on our docker compose
- Using a fixed version of matomo source image (using previous one)
- building the image on github actions
- using ghcr image in compose
> building matomo in Github

- docker-compose.yml
For some reason, monitoring.openzim.org being in the reverse-proxy's letsencrypt list
makes the certificate renewal request for the reverse-proxy to fail (third party
python code raises an exception).
Given it's not necessary for this particular domain and the coming switch to k8s,
removing it is a interval fix.
> Removed monitoring.openzim.org from HTTPS list

- docker-compose.yml
- offspot-drive has been migrated to k8s
- zimfarm-drive has been migrated to k8s
- monitoring is disabled for now (we'll revive it on k8s later)
- dev-library is disabled for now (we'll revive it on k8s later)
Commenting on purpose for now.
> Commenting obsolete services

- docker-compose.yml
Server is configured with `assume_secure_protocol=1` which creates a 308 redirect
to https version which the log upload script complains about
> Use HTTPS url for log upload

- .github/workflows/kiwix-build_ci.yml
- kiwix-build_ci/README.md
- kiwix-build_ci/alpine_builder.dockerfile
- kiwix-build_ci/bionic_builder.dockerfile
- kiwix-build_ci/f35_builder.dockerfile
- kiwix-build_ci/focal_builder.dockerfile
openZIM and Kiwix CI/CD kiwix-build usage relies on container images with ready-to-use compilation environments.
These container images have been prepared within the kiwix-build repository so far, but this had a few inconveniences:
* Kiwix-build doing already many things, this was not simplifying the situation (see https://github.com/kiwix/kiwix-build/wiki/Kiwix-Build-usage-in-CI-&-CD).
* It's not the primary role anyway of Kiwix-build repository to prepare its runtime environment in the special use case of our CI/CD
* We have a dedicated repository for creating our container images and it's here
The only thing which has changed from the user point-of-view is that instead of making a Github release to generate a new release of the images, each time we merge to `main`, then a new tag with …
> Import Kiwix-build container images

- mirrorbrain/Dockerfile
Mirrobrain scanner has a `$gig2` variable set at 2GiB It is used as a threshold on rsync scans
Files larger than it trigger a Range-Request HTTP download. If the request fails a warning is printed
Those requests are not necessary and create load on mirrors
This changes this variable value to 256GiB
> Changing mirrorbrain's check_large_file threshold

- .github/workflows/maintenance_ci.yml
- kiwix-build_ci/noble_builder.dockerfile
This is necessary to [build Kiwix Desktop on recent version of Qt6 in CI](https://github.com/kiwix/kiwix-desktop/issues/1103)
> Noble CI image

- .github/workflows/kiwix-build_ci.yml
- kiwix-build_ci/jammy_builder.dockerfile
Sooner or later we will have to upgrade our Linux build platform from focal to jammy. This PR enables us to do it sooner than later.
Once available, the jammy builder can be immediately utilized for [creating the kiwix-desktop appimage](https://github.com/kiwix/kiwix-desktop/issues/1219#issuecomment-2425016073).
> Added jammy builder dockerfile

- kiwix-build_ci/manylinux_builder.dockerfile
This PR is an attempt to fix CI for https://github.com/kiwix/kiwix-build/pull/771
Because the `FROM` of the Manylinux was not pinned, latest rebuild has made our `anylinux_builder.dockerfile` obselete in a way which was only detectable later at run (bad `$ENV` variable).
This is exactly to avoid this kind of hassle that all dependencies should always be fixed/pinned!
I don't understand why we have all these tools installed outside the system paths, which then generate the need of a customized `$PATH`. But I have decided to be conservative and just keep this approach and fix things using the current approach.
> Update and pin Manylinux CI `FROM` image

- maintenance/install_scripts.py
With this PR, `install_script.py` can install the script from any github branch, specified with a `?branch=xxx` query in URI.
E.g. if one want to install script in `kiwix/operations` repo on `test` branch at `zim/library-mgmt/library-maint.py`, the URI to use will be `github://kiwix/operations/zim/library-mgmt/library-maint.py?branch=test`
Useful mostly for testing scripts in a branch before merging a PR (or even before submitting the PR, depending on the difficulty).
> Add support for installing script from any branch

- kiwix-build_ci/noble_builder.dockerfile
Built this noble-based image locally and I can now use `qmake` command instead of `qmake6` to invoke the build. This helps keep the [kiwix-desktop CI](https://github.com/kiwix/kiwix-desktop/blob/a64806061b77687552e0102d259e6ae0ebf36204/.github/workflows/ci.yml#L84) the same between qt5 and qt6.
Related to https://github.com/kiwix/kiwix-desktop/issues/1103.
> Noble image builds with qmake instead of qmake6

- kiwix-build_ci/oracular_builder.dockerfile
Ubuntu Oracular 24.10 contains Qt 6.6, so it should be a good CI environment to ensure compatibility with a more recent Qt version.
> Add oracular to kiwix-build_ci

- kiwix-build_ci/jammy_builder.dockerfile
We want to ease Qt6 based Kiwix Desktop 2.5.0+ compilation.
See https://github.com/kiwix/kiwix-build/issues/594
> Add packages to ease Qt6 Kiwix-Desktop compil.

- kiwix-build_ci/alpine_builder.dockerfile
- kiwix-build_ci/f35_builder.dockerfile
- kiwix-build_ci/focal_builder.dockerfile
- kiwix-build_ci/jammy_builder.dockerfile
- kiwix-build_ci/manylinux_builder.dockerfile
- kiwix-build_ci/noble_builder.dockerfile
- kiwix-build_ci/oracular_builder.dockerfile
In builder images released on 2025-06-06 meson was upgraded to version 1.8.1 compared to version 1.6.1 found in the previous release on 2025-01-05. That change resulted in certain failures in kiwix-build CI. Hence this PR.
> Forced meson to v1.6.1 in builder images
