kiwix/container-images

mirrorbrain-docker/config/mirrorbrain/mirrorbrain.conf
@florentk If OK, please merge and update container on download.kiwix.org.
Fix #37
=> Add zsync URL support #37

docker-compose.yml, reverse-proxy-docker/sites/download.cardshop.hotspot.kiwix.org
Cardshop users will download their images from there.
Once merged, **please deploy** as well.
=> Added a reverse-proxy conf for download.cardshop.hotspot.kiwix.org

matomo-log-analytics-docker/Dockerfile
=> Enable redirects tracking in Matomo

reverse-proxy-docker/Dockerfile
Please don't forget to deploy, when merged.
=> Gzip only text stuff

mirrorbrain-docker/config/apache/httpd-vhosts.conf
Fix #61
@florentk Please deploy it if OK to you
=> Add CORS authorization to the HTTP header

mirrorbrain-docker/bin/update_mirrorbrain_db.sh
=> Update mirrorbrain fo better deal with mirror.tn mirror

docker-compose.yml, reverse-proxy-docker/sites/logs.warehouse.farm.openzim.org
Serves `/data/zimfarm-warehouse/logs/`
=> Added HTTP(s) service for zimfarm warehouse logs download (

docker-compose.yml
@florentk May you please review this PR, restart the service and verify the logs are written properly please?
=> Run zimcheck

docker-compose.yml
remove quotes in env for cardshop IP as well.
=> removing quotes on cardshop IP as well

campusafrica/README.md, campusafrica/docker-compose.yml, campusafrica/kalite-docker/kalite-setup.sh, campusafrica/logger/Dockerfile, campusafrica/logger/crontab, campusafrica/logger/entrypoint.sh, campusafrica/logger/format_and_exit.patch, campusafrica/logger/reload-nginx.py, campusafrica/logger/rotate_logger, campusafrica/logger/upload-log.sh, campusafrica/logger/upload-logs.py
- dedicated container that
- rotate logs on host using a mounted logrotate config file
- upload logs to stats.kiwix.org
- compress uploaded logs
- ask nginx to reopen its log file on rotate
=> added log rotation and upload to campus

campusafrica/docker-compose.yml, campusafrica/home/gen_homepages.py, campusafrica/home/home_template.html, campusafrica/vhost.d/zims-lfr.kiwix.campusafrica.gos.orange.com_location
special version of french homepage vithout video content
- tweaked home page without video zims and kalite
- dedicated kiwix-serve with only non-video zims
=> added lfr kiwix serve and home page

library-docker/bin/start.sh
=> Better retry system

library-docker/bin/start.sh
=> Disallow Web Spider (to avoid DOS)

reverse-proxy-docker/12createReleaseFeeds, reverse-proxy-docker/Dockerfile, reverse-proxy-docker/genrss.patch
=> Create software release feeds automatically

library-docker/bin/manageContentRepository.pl, reverse-proxy-docker/11createReleaseRedirects, reverse-proxy-docker/Dockerfile, reverse-proxy-docker/sites/download.openzim.org
Fixes https://github.com/kiwix/kiwix-build/issues/448
=> Create permalinks for openZIM releases

reverse-proxy-docker/sites/download.openzim.org
Fixes https://github.com/kiwix/maintenance/issues/128
=> Use 301 redirects without cache in place of 302 

mirrorbrain-docker/config/apache/httpd.conf, reverse-proxy-docker/Dockerfile
Fixes #143 
- changed un apache config for download.kiwix
- changed un reverse-proxy nginx for mirror.download.kiwix
=> Serve APK with proper mime type

docker-compose.yml, matomo-server-docker/data/mysql/conf/pool.cnf, matomo-server-docker/data/mysql/conf/timeout.cnf, matomo-server-docker/docker-compose.yml
@florentk This is an attemps to fix #162
=> Matomo Mysql configuration should be in git

docker-compose.yml
To fix https://github.com/openzim/zimfarm/issues/499
=> Moved quarantine folder to a subfolder of zimfarm-quarantine

library-docker/bin/manageContentRepository.pl
Partly fix https://github.com/kiwix/kiwix-hotspot/issues/576
=> Add a few redirects for latest Kiwix Hotspot masters

.github/workflows/docker.yml
Create our docker images in GHA and upload them to docker hub and GHCR
=> Add docker publish support

.github/workflows/docker.yml, docker-compose.yml
- only upload built images to ghcr.io
- use ghcr.io versions of our images in docker-compose
=> Use only ghcr.io

library-docker/Dockerfile
=> Use kiwix-serve 3.2.0 for library.kiwix.org

library-docker/Dockerfile
To benefit of latest libkiwix 10.0.1
=> Use kiwix-tools 3.2.0-1

library-docker/Dockerfile
@rgaudin Please deploy it too.
=> Use kiwix-serve 3.2.0-3

dropbox/Dockerfile, dropbox/README.md, dropbox/create-user.py, dropbox/entrypoint.py, dropbox/sshd_config
Changed from single, static `ci` user to a dynamic list of users,
each with ability to customize uid and keys from a single JSON environ.
=> Multiple Users support

mirrorbrain/bin/update_mirrorbrain_db.sh
=> DIRS should contain only topmost folder in the hierarchy

dropbox/Dockerfile
Add fail2ban to Dropbox container image
Fixes #227
=> Add failban service

maintenance/Dockerfile
- Upgrade to Python 3.12
- Upgrade Python dependencies (including scraperlib 4.0 breaking changes ... it is time to move on ^^)
- Add `pydantic` to already installed deps
=> Upgrade maintenance image and add pydantic
